use nnte;
select * from BASE_SYS_PARAM;
/*
insert into BASE_SYS_PARAM(PARAM_TYPE,PARAM_NAME,PAR_MERCHANT_ID,CLASS_ID,PKEY,VALUE1,VALUE2,VALUE5,VALUE_TEXT,PARAM_STATE)
values('MM','商户报表业务类型',1,'SYSPARAM_MERCHANT_REPORT_BUSI_TYPE','CG','采购报表','','','',1);
insert into BASE_SYS_PARAM(PARAM_TYPE,PARAM_NAME,PAR_MERCHANT_ID,CLASS_ID,PKEY,VALUE1,VALUE2,VALUE5,VALUE_TEXT,PARAM_STATE)
values('MM','商户报表业务类型',1,'SYSPARAM_MERCHANT_REPORT_BUSI_TYPE','XS','销售报表','','','',1);
insert into BASE_SYS_PARAM(PARAM_TYPE,PARAM_NAME,PAR_MERCHANT_ID,CLASS_ID,PKEY,VALUE1,VALUE2,VALUE5,VALUE_TEXT,PARAM_STATE)
values('MM','商户报表业务类型',1,'SYSPARAM_MERCHANT_REPORT_BUSI_TYPE','KC','库存报表','','','',1);

insert into BASE_SYS_PARAM(PARAM_TYPE,PARAM_NAME,PAR_MERCHANT_ID,CLASS_ID,PKEY,VALUE1,VALUE2,VALUE5,VALUE_TEXT,PARAM_STATE)
values('MS','商户数据导出每页行数',1,'','MERCHANT_EXPORT_EXCEL_SHEET_COUNT','200','','','',1);

*/
select * from MERCHANT_REPORT_DEFINE;
select * from MERCHANT_DBCONNECT_DEFINE;
select * from MERCHANT_REPORT_QUERY;